# Generated by Django 2.0.3 on 2018-04-16 06:06

from django.db import migrations
import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='amount',
            field=djstripe.fields.StripeCurrencyField(decimal_places=2, help_text='Amount to be charged on the interval specified.', max_digits=8, null=True),
        ),
    ]
